CREATE TABLE APP_USER (
   id SERIAL NOT NULL PRIMARY KEY,
   name VARCHAR(200) NOT NULL,
   email VARCHAR(500) NOT NULL,
   pw VARCHAR(500) NOT NULL
);

CREATE TABLE ALLERGY (
   id SERIAL NOT NULL PRIMARY KEY,
   name VARCHAR(30) NOT NULL
);

CREATE TABLE USER_ALLERGY (
   id SERIAL NOT NULL PRIMARY KEY,
   user_id INT NOT NULL REFERENCES APP_USER(id),
   allergy_id INT NOT NULL REFERENCES ALLERGY(id)
);
